### ISSUE TITLE
英語版のOGP画像が「東京都」になっている

### ISSUE THREAD

**Issue by nukaga** [codeforkagawa/covid19#22]
## 起こっている問題 / The Problem
- 英語ページのURL( https://kagawa.stopcovid19.jp/en ) をSNSで共有するとOGP画像が「東京都」になっています

## スクリーンショット / Screenshot
<img width="566" alt="スクリーンショット 2020-04-08 20 19 41" src="https://user-images.githubusercontent.com/3480985/78778519-5be64000-79d6-11ea-943b-744150f3fcd0.png">

## 期待する見せ方・挙動 / Expected Behavior
-  https://kagawa.stopcovid19.jp/en をシェアした時にも香川県のOGPを表示させたいです

## 起こっている問題の再現手段 / Steps to Reproduce
1. Facebook デバッカー https://developers.facebook.com/tools/debug/ に https://kagawa.stopcovid19.jp/en を入れる
2. Twitter Card validator https://cards-dev.twitter.com/validator にhttps://kagawa.stopcovid19.jp/en を入れる

プルリクエストできるといいのですが、直す箇所がわかりませんでした。すみませんが該当箇所を教えていただくか、直していただけると嬉しいです。

**Comment by nandehu0323** [comment]
バグ報告ありがとうございます！
即刻修正させていただきます🙇‍♂️

**Comment by nukaga** [comment]
ありがとうございます！
